#include <cstdlib>

enum class ExitCode : int {
  SUCCESS = 0,
  ATTACH_FAILED = 1,
  GET_REGISTERS_AFTER_ATTACH_FAILED = 2,
  SET_INJECTED_SHELLCODE_REGISTERS_FAILED = 3,
  READ_TARGET_MEMORY_FAILED = 4,
  WRITE_SHELLCODE_TO_TARGET_MEMORY_FAILED = 5,
  ERROR_IN_EXECUTE_MALLOC = 6,
  GET_MALLOC_REGISTERS_FAILED = 7,
  MALLOC_RETURN_ZERO = 8,
  WRITE_LIBRARY_STR_TO_TARGET_MEMORY_FAILED = 9,
  ERROR_IN_EXECUTE_DLOPEN = 10,
  GET_DLOPEN_REGISTERS_FAILED = 11,
  DLOPEN_RETURN_ZERO = 12,
  ERROR_IN_EXECUTE_FREE = 13,
  ERROR_IN_EXECUTE_RECOVER_INJECTION = 14,
  ERROR_IN_VERIFY_SO_LOCATION = 15,
  ERROR_FLIGHT_SERVER_NO_RESPONSE = 16,
};
